'use client';
import {use,useEffect,useMemo,useState} from 'react';
import styles from './work.module.css';
export default function WorkPage({params}){
 const {token}=use(params);const [work,setWork]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[km,setKm]=useState(''),[tripType,setTripType]=useState('retour'),[note,setNote]=useState('');
 async function load(){const r=await fetch(`/api/worklink/${encodeURIComponent(token)}`,{cache:'no-store'}),j=await r.json();if(!r.ok)throw new Error(j.error||'Laden mislukt');setWork(j.work);setKm(String(j.work.kilometers||''));setTripType(j.work.tripType||'retour');setNote(j.work.note||'')}
 useEffect(()=>{load().catch(e=>setError(e.message));const t=setInterval(()=>load().catch(()=>{}),30000);return()=>clearInterval(t)},[token]);
 async function action(name,extra={}){setBusy(true);setError('');try{const r=await fetch(`/api/worklink/${encodeURIComponent(token)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:name,...extra})}),j=await r.json();if(!r.ok)throw new Error(j.error||'Opslaan mislukt');setWork(j.work)}catch(e){setError(e.message)}finally{setBusy(false)}}
 const elapsed=useMemo(()=>{if(!work?.clockIn)return'00:00';const end=work.clockOut?new Date(work.clockOut):new Date();let m=Math.max(0,Math.floor((end-new Date(work.clockIn))/60000)-(work.pauseMinutes||0));return`${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`},[work]);
 if(error&&!work)return <main className={styles.page}><div className={styles.error}>{error}</div></main>;if(!work)return <main className={styles.page}>Werklink laden…</main>;
 return <main className={styles.page}><header className={styles.header}><img src="/gio-logo-192.png" alt="GIO"/><div><b>GIO Business Planner</b><small>Werklink PRO</small></div></header>
 <section className={styles.profile}>{work.employeePhoto?<img src={work.employeePhoto} alt=""/>:<div className={styles.avatar}>👷</div>}<div><small>Welkom</small><h1>{work.employeeName}</h1><span>{work.employeeType||'Medewerker'}</span></div></section>
 <section className={styles.job}><div><small>Project</small><b>{work.projectName}</b></div><div><small>Klant</small><b>{work.customerName||'—'}</b></div><div><small>Adres</small><b>{work.workAddress||'—'}</b></div><div><small>Datum</small><b>{work.workDate?new Date(work.workDate+'T12:00:00').toLocaleDateString('nl-NL'):'—'}</b></div>{work.assignment&&<p>{work.assignment}</p>}</section>
 <section className={styles.clock}><small>Status</small><h2>{work.status}</h2><div className={styles.timer}>{elapsed}</div><div className={styles.buttons}>{['Niet gestart','Uitgeklokt'].includes(work.status)&&<button className={styles.primary} disabled={busy} onClick={()=>action('clock_in')}>▶ Inklokken</button>}{work.status==='Ingeklokt'&&<><button disabled={busy} onClick={()=>action('pause')}>⏸ Pauze</button><button className={styles.stop} disabled={busy} onClick={()=>action('clock_out')}>■ Uitklokken</button></>}{work.status==='Pauze'&&<><button className={styles.primary} disabled={busy} onClick={()=>action('resume')}>▶ Hervatten</button><button className={styles.stop} disabled={busy} onClick={()=>action('clock_out')}>■ Uitklokken</button></>}</div>{work.clockIn&&<small>Ingeklokt: {new Date(work.clockIn).toLocaleString('nl-NL')}</small>}</section>
 {work.allowKm&&<section className={styles.form}><h3>🚗 Kilometers</h3><div className={styles.row}><input type="number" min="0" step="0.1" value={km} onChange={e=>setKm(e.target.value)} placeholder="Aantal km"/><select value={tripType} onChange={e=>setTripType(e.target.value)}><option value="retour">Heen en terug</option><option value="enkel">Enkele reis</option></select></div><button disabled={busy} onClick={()=>action('save_km',{kilometers:km,tripType})}>KM opslaan</button></section>}
 {work.allowNote&&<section className={styles.form}><h3>📝 Werknotitie</h3><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Korte notitie over de klus"/><button disabled={busy} onClick={()=>action('save_note',{note})}>Notitie opslaan</button></section>}{error&&<div className={styles.error}>{error}</div>}<footer>Alleen toegewezen werkgegevens zijn zichtbaar.</footer></main>
}
