'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {supabase} from '../lib/supabaseClient';
const empty={klanten:[],projecten:[],planning:[],uren:[],materiaal:[],uitgaven:[],notities:[]};
const cats=['⛽ Benzine / Tanken','🔌 Auto laden','🚗 Auto onderhoud','🚘 Auto huur','🛞 Banden','🅿️ Parkeren','✈️ Vlucht','🏨 Overnachting / Hotel','🍔 Eten onderweg','☕ Koffie / Lunch','🍽️ Zakelijk diner','🔧 Gereedschap','🦺 Werkkleding','📱 Telefoon','💻 Software / Abonnementen','📋 Administratie','📦 Overige bedrijfskosten'];
const statuses=['Offerte','Gepland','In uitvoering','Werk done','Factureren','Factuur verzonden','Betaald'];
const euro=v=>new Intl.NumberFormat('nl-NL',{style:'currency',currency:'EUR'}).format(Number(v||0));
const today=()=>new Date().toISOString().slice(0,10);
const dnl=d=>{if(!d)return'';let p=String(d).split('-');return p.length===3?`${p[2]}/${p[1]}/${p[0].slice(2)}`:d};
function nr(prefix,arr,field){let y=String(new Date().getFullYear()),m=0;(arr||[]).forEach(x=>{let r=String(x[field]||'').match(new RegExp('^'+prefix+y+'-(\\d+)$'));if(r)m=Math.max(m,parseInt(r[1],10))});return prefix+y+'-'+String(m+1).padStart(3,'0')}
function mins(t){let [h,m]=String(t||'00:00').split(':').map(Number);return h*60+m}
const clean=d=>({...empty,...(d||{}),vrijeDagen:d?.vrijeDagen||d?.vrijedagen||[]});
export default function Home(){
 const [session,setSession]=useState(null),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[active,setActive]=useState('dashboard'),[data,setData]=useState(empty),[sync,setSync]=useState('Start...');
 const [klant,setKlant]=useState({type:'Privé'}),[project,setProject]=useState({status:'Gepland',methode:'Regie / urenbasis'}),[plan,setPlan]=useState({datum:today(),eindDatum:today(),start:'08:00',einde:'16:30'}),[uur,setUur]=useState({datum:today(),start:'08:00',einde:'16:30',tarief:35}),[mat,setMat]=useState({datum:today(),bedrag:0}),[uit,setUit]=useState({datum:today(),categorie:cats[0],bedrag:0,btwPerc:21}),[note,setNote]=useState({datum:today()}),[importText,setImportText]=useState('');
 const loaded=useRef(false),timer=useRef(null);
 useEffect(()=>{if(!supabase){loadLocal();setSync('Offline');return}supabase.auth.getSession().then(({data})=>setSession(data.session));const {data:sub}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>sub.subscription.unsubscribe()},[]);
 useEffect(()=>{if(session?.user)loadCloud()},[session?.user?.id]);
 useEffect(()=>{localStorage.setItem('gioBusinessPlannerV1',JSON.stringify(data));if(loaded.current&&session?.user&&supabase){clearTimeout(timer.current);timer.current=setTimeout(saveCloud,700)}},[data]);
 function loadLocal(){for(const k of ['gioBusinessPlannerV1','gioTestBetaald','gioTestDesktop','gioPlannerDesktop']){let raw=localStorage.getItem(k);if(raw){try{setData(clean(JSON.parse(raw)));break}catch{}}}}
 async function loadCloud(){loadLocal();setSync('Cloud laden...');let {data:row,error}=await supabase.from('planner_data').select('data').eq('user_id',session.user.id).maybeSingle();if(error){setSync('Cloud fout: '+error.message);return}if(row?.data){setData(clean(row.data));setSync('Cloud geladen')}else setSync('Nieuwe cloud klaar');loaded.current=true}
 async function saveCloud(){let {error}=await supabase.from('planner_data').upsert({user_id:session.user.id,data,updated_at:new Date().toISOString()},{onConflict:'user_id'});setSync(error?'Opslaan fout: '+error.message:'Opgeslagen in cloud')}
 async function login(){let {error}=await supabase.auth.signInWithPassword({email,password});if(error)alert(error.message)}
 async function signup(){let {error}=await supabase.auth.signUp({email,password});alert(error?error.message:'Account gemaakt. Log nu in.')}
 async function logout(){await supabase.auth.signOut();setSession(null)}
 function totals(n){let us=data.uren.filter(x=>x.project===n),ms=data.materiaal.filter(x=>x.project===n);let uren=us.reduce((s,x)=>s+Number(x.uren||0),0),arbeid=us.reduce((s,x)=>s+Number(x.bedrag||0),0),materiaal=ms.reduce((s,x)=>s+Number(x.bedrag||0),0);return{uren,arbeid,materiaal,totaal:arbeid+materiaal}}
 const dash=useMemo(()=>{let omzet=data.uren.reduce((s,x)=>s+Number(x.bedrag||0),0),mk=data.materiaal.reduce((s,x)=>s+Number(x.bedrag||0),0),uitg=data.uitgaven.reduce((s,x)=>s+Number(x.bedrag||0),0);let val=p=>p.methode==='Volgens offerte / vaste prijs'?Number(p.offerteBedrag||0):totals(p.naam).totaal;return{omzet,mk,uitg,winst:omzet-mk-uitg,tf:data.projecten.filter(p=>p.status==='Factureren').reduce((s,p)=>s+val(p),0),verz:data.projecten.filter(p=>p.status==='Factuur verzonden').reduce((s,p)=>s+val(p),0),betaald:data.projecten.filter(p=>p.status==='Betaald').reduce((s,p)=>s+val(p),0),open:data.projecten.filter(p=>p.status!=='Betaald').reduce((s,p)=>s+totals(p.naam).materiaal,0)}},[data]);
 function saveKlant(){if(!klant.naam)return alert('Vul klantnaam in');let item={...klant,klantNr:klant.klantNr||nr('K',data.klanten,'klantNr'),gewijzigdOp:new Date().toLocaleString('nl-NL')};setData(d=>({...d,klanten:[...d.klanten.filter(k=>k.klantNr!==item.klantNr),item]}));setKlant({type:'Privé'})}
 function saveProject(){if(!project.naam)return alert('Vul projectnaam in');let item={...project,projectNr:project.projectNr||nr('',data.projecten,'projectNr')};setData(d=>({...d,projecten:[...d.projecten.filter(p=>p.projectNr!==item.projectNr),item]}));setProject({status:'Gepland',methode:'Regie / urenbasis'})}
 function setStatus(projectNr,status){setData(d=>({...d,projecten:d.projecten.map(p=>{if(p.projectNr!==projectNr)return p;let n={...p,status,statusDatum:new Date().toLocaleString('nl-NL')};if(['Factureren','Factuur verzonden','Betaald'].includes(status)&&!n.factuurNr)n.factuurNr=nr('F',d.projecten,'factuurNr');if(status==='Betaald')n.betaaldDatum=today();return n})}))}
 function savePlan(){if(!plan.project)return alert('Kies project');setData(d=>({...d,planning:[...d.planning,{...plan,id:String(Date.now())}]}))}
 function saveUur(){if(!uur.project)return alert('Kies project');let m=mins(uur.einde)-mins(uur.start);if(m<0)m+=1440;let uren=m/60,bedrag=uren*Number(uur.tarief||35);setData(d=>({...d,uren:[...d.uren,{...uur,uren,bedrag}]}))}
 function saveMat(){if(!mat.project)return alert('Kies project');setData(d=>({...d,materiaal:[...d.materiaal,mat]}));setMat({datum:today(),bedrag:0})}
 function saveUit(){let b=Number(uit.bedrag||0),p=Number(uit.btwPerc||0);setData(d=>({...d,uitgaven:[...d.uitgaven,{...uit,btwBedrag:p?b-b/(1+p/100):0}]}));setUit({datum:today(),categorie:cats[0],bedrag:0,btwPerc:21})}
 function saveNote(){if(!note.project||!note.text)return alert('Kies project en vul notitie in');setData(d=>({...d,notities:[...(d.notities||[]),{...note,id:String(Date.now())}]}));setNote({datum:today()})}
 function del(list,i){if(confirm('Verwijderen?'))setData(d=>({...d,[list]:d[list].filter((_,idx)=>idx!==i)}))}
 function exportBackup(){let blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='GIO_Backup_'+today()+'.json';a.click()}
 function importBackup(){try{setData(clean(JSON.parse(importText)));loaded.current=true;alert('Geïmporteerd')}catch{alert('Kan JSON niet lezen')}}
 function file(e){let f=e.target.files?.[0];if(!f)return;let r=new FileReader();r.onload=()=>setImportText(String(r.result||''));r.readAsText(f)}
 if(!session&&supabase)return <div className="login"><h1>GIO Business Planner</h1><label>E-mail</label><input value={email} onChange={e=>setEmail(e.target.value)}/><label>Wachtwoord</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)}/><button className="primary" onClick={login}>Inloggen</button><button className="dark" onClick={signup}>Account aanmaken</button><p className="small">Data wordt na login in Supabase opgeslagen.</p></div>;
 const nav=[['dashboard','🏠 Dashboard'],['klanten','👥 Klanten'],['projecten','📁 Projecten'],['planning','📅 Planning'],['uren','⏱ Uren'],['materiaal','🧰 Materiaal'],['uitgaven','💸 Uitgave / Investeren'],['notities','📝 Notities'],['backup','💾 Back-up / Import']];
 return <div className="shell"><aside className="sidebar"><div className="logo">GIO Business Planner</div><div className="sub">LIVE v1.0</div><div className="nav">{nav.map(([id,l])=><button key={id} className={active===id?'active':''} onClick={()=>setActive(id)}>{l}</button>)}</div></aside><main className="main"><div className="topbar"><div><b>GIO Business Planner</b><br/><small className={sync.includes('fout')?'bad':'ok'}>{sync}</small></div><div><button className="primary" onClick={exportBackup}>💾 Back-up</button>{session&&<button className="dark" onClick={logout}>Uitloggen</button>}</div></div>
 {active==='dashboard'&&<><div className="grid">{[['Omzet',dash.omzet],['Materiaal klant',dash.mk],['Uitgaven',dash.uitg],['Winst',dash.winst],['Te factureren',dash.tf],['Factuur verzonden',dash.verz],['Open materiaal',dash.open],['Betaald',dash.betaald]].map(([l,v])=><Kpi key={l} label={l} value={v}/>)}</div><ProjectTable data={data} totals={totals} setProject={setProject} setStatus={setStatus}/></>}
 {active==='klanten'&&<><FormCard title="👥 Klant toevoegen / wijzigen"><div className="row"><Field label="Type"><select value={klant.type||'Privé'} onChange={e=>setKlant({...klant,type:e.target.value})}><option>Privé</option><option>Zakelijk</option></select></Field>{['naam','contact','adres','postcode','plaats','telefoon','email','factuurEmail','kvk','btw'].map(f=><Field key={f} label={f}><input value={klant[f]||''} onChange={e=>setKlant({...klant,[f]:e.target.value})}/></Field>)}</div><button className="primary" onClick={saveKlant}>Klant opslaan</button></FormCard><Table title="Klantenbestand" head={['Klantnr','Type','Naam','Plaats','Telefoon','E-mail','Wijzig','']} rows={data.klanten.map((k,i)=>[k.klantNr,k.type,k.naam,k.plaats,k.telefoon,k.email,<button className="dark" onClick={()=>setKlant(k)}>✏️</button>,<button className="red" onClick={()=>del('klanten',i)}>🗑️</button>])}/></>}
 {active==='projecten'&&<><ProjectForm data={data} project={project} setProject={setProject} saveProject={saveProject}/><ProjectTable data={data} totals={totals} setProject={setProject} setStatus={setStatus}/><ProjectDetails data={data} totals={totals}/></>}
 {active==='planning'&&<FormCard title="📅 Planning"><div className="row"><ProjectSelect data={data} value={plan.project} onChange={v=>setPlan({...plan,project:v})}/><Field label="Startdatum"><input type="date" value={plan.datum||today()} onChange={e=>setPlan({...plan,datum:e.target.value})}/></Field><Field label="Einddatum"><input type="date" value={plan.eindDatum||today()} onChange={e=>setPlan({...plan,eindDatum:e.target.value})}/></Field><Field label="Start"><input type="time" value={plan.start||''} onChange={e=>setPlan({...plan,start:e.target.value})}/></Field><Field label="Einde"><input type="time" value={plan.einde||''} onChange={e=>setPlan({...plan,einde:e.target.value})}/></Field><Field label="Door"><input value={plan.door||''} onChange={e=>setPlan({...plan,door:e.target.value})}/></Field></div><label>Notitie</label><input value={plan.notitie||''} onChange={e=>setPlan({...plan,notitie:e.target.value})}/><button className="primary" onClick={savePlan}>Planning opslaan</button><SimpleRows items={data.planning} cols={['project','datum','eindDatum','start','einde','door','notitie']}/></FormCard>}
 {active==='uren'&&<FormCard title="⏱ Uren"><div className="row"><Field label="Datum"><input type="date" value={uur.datum} onChange={e=>setUur({...uur,datum:e.target.value})}/></Field><Field label="Klant"><select value={uur.klant||''} onChange={e=>setUur({...uur,klant:e.target.value})}><option></option>{data.klanten.map(k=><option key={k.klantNr}>{k.naam}</option>)}</select></Field><ProjectSelect data={data} value={uur.project} onChange={v=>setUur({...uur,project:v})}/>{['start','einde','tarief'].map(f=><Field key={f} label={f}><input type={f==='tarief'?'number':'time'} value={uur[f]||''} onChange={e=>setUur({...uur,[f]:e.target.value})}/></Field>)}</div><button className="primary" onClick={saveUur}>Uren opslaan</button><Table head={['Datum','Klant','Project','Start','Einde','Uren','Bedrag']} rows={data.uren.map(u=>[dnl(u.datum),u.klant,u.project,u.start,u.einde,Number(u.uren||0).toFixed(2),euro(u.bedrag)])}/></FormCard>}
 {active==='materiaal'&&<FormCard title="🧰 Materiaal"><div className="row"><Field label="Datum"><input type="date" value={mat.datum} onChange={e=>setMat({...mat,datum:e.target.value})}/></Field><ProjectSelect data={data} value={mat.project} onChange={v=>setMat({...mat,project:v})}/>{['lev','oms','bedrag','pdfNaam'].map(f=><Field key={f} label={f}><input type={f==='bedrag'?'number':'text'} value={mat[f]||''} onChange={e=>setMat({...mat,[f]:e.target.value})}/></Field>)}</div><button className="primary" onClick={saveMat}>Materiaal opslaan</button><Table head={['Datum','Project','Leverancier','Materiaal','Bedrag','Bon/PDF']} rows={data.materiaal.map(x=>[dnl(x.datum),x.project,x.lev,x.oms,euro(x.bedrag),x.pdfNaam])}/></FormCard>}
 {active==='uitgaven'&&<FormCard title="💸 Uitgave / Investeren"><div className="row"><Field label="Datum"><input type="date" value={uit.datum} onChange={e=>setUit({...uit,datum:e.target.value})}/></Field><Field label="Categorie"><select value={uit.categorie} onChange={e=>setUit({...uit,categorie:e.target.value})}>{cats.map(c=><option key={c}>{c}</option>)}</select></Field>{['leverancier','omschrijving','bedrag','btwPerc','pdfNaam'].map(f=><Field key={f} label={f}><input type={['bedrag','btwPerc'].includes(f)?'number':'text'} value={uit[f]||''} onChange={e=>setUit({...uit,[f]:e.target.value})}/></Field>)}</div><button className="primary" onClick={saveUit}>Uitgave opslaan</button><Table head={['Datum','Categorie','Leverancier','Omschrijving','Bedrag','BTW','Bon/PDF']} rows={data.uitgaven.map(x=>[dnl(x.datum),x.categorie,x.leverancier,x.omschrijving,euro(x.bedrag),euro(x.btwBedrag),x.pdfNaam])}/></FormCard>}
 {active==='notities'&&<FormCard title="📝 Notities"><div className="row"><Field label="Datum"><input type="date" value={note.datum} onChange={e=>setNote({...note,datum:e.target.value})}/></Field><ProjectSelect data={data} value={note.project} onChange={v=>setNote({...note,project:v})}/></div><label>Notitie</label><textarea value={note.text||''} onChange={e=>setNote({...note,text:e.target.value})}/><button className="primary" onClick={saveNote}>Notitie opslaan</button><Table head={['Datum','Project','Notitie']} rows={(data.notities||[]).map(n=>[dnl(n.datum),n.project,n.text])}/></FormCard>}
 {active==='backup'&&<FormCard title="💾 Back-up / Import"><div className="notice">Importeer hier je oude testdata. Na import slaat de planner automatisch op in Supabase.</div><br/><button className="primary" onClick={exportBackup}>Back-up maken</button><label>JSON bestand</label><input type="file" accept=".json" onChange={file}/><label>JSON plakken</label><textarea value={importText} onChange={e=>setImportText(e.target.value)}/><button className="dark" onClick={importBackup}>Importeren</button><div className="code">{JSON.stringify(data,null,2).slice(0,4000)}</div></FormCard>}
 </main></div>}
function Field({label,children}){return <div><label>{label}</label>{children}</div>}
function Kpi({label,value}){return <div className="kpi"><small>{label}</small><b>{euro(value)}</b></div>}
function FormCard({title,children}){return <div className="card"><h2>{title}</h2>{children}</div>}
function ProjectSelect({data,value,onChange}){return <Field label="Project"><select value={value||''} onChange={e=>onChange(e.target.value)}><option></option>{data.projecten.map(p=><option key={p.projectNr}>{p.naam}</option>)}</select></Field>}
function ProjectForm({data,project,setProject,saveProject}){return <FormCard title="📁 Project toevoegen / wijzigen"><div className="row"><Field label="Projectnaam"><input value={project.naam||''} onChange={e=>setProject({...project,naam:e.target.value})}/></Field><Field label="Klant"><select value={project.klant||''} onChange={e=>setProject({...project,klant:e.target.value})}><option></option>{data.klanten.map(k=><option key={k.klantNr}>{k.naam}</option>)}</select></Field><Field label="Status"><select value={project.status||'Gepland'} onChange={e=>setProject({...project,status:e.target.value})}>{statuses.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Methode"><select value={project.methode||'Regie / urenbasis'} onChange={e=>setProject({...project,methode:e.target.value})}><option>Regie / urenbasis</option><option>Volgens offerte / vaste prijs</option></select></Field><Field label="Offertebedrag"><input type="number" value={project.offerteBedrag||''} onChange={e=>setProject({...project,offerteBedrag:e.target.value})}/></Field><Field label="Startdatum"><input type="date" value={project.start||''} onChange={e=>setProject({...project,start:e.target.value})}/></Field><Field label="Einddatum"><input type="date" value={project.eind||''} onChange={e=>setProject({...project,eind:e.target.value})}/></Field></div><button className="primary" onClick={saveProject}>Project opslaan</button></FormCard>}
function ProjectTable({data,totals,setProject,setStatus}){return <div className="card"><h2>📁 Projectoverzicht</h2><table><thead><tr><th>Projectnr.</th><th>Project</th><th>Klant</th><th>Methode</th><th>Status</th><th>Arbeid</th><th>Materiaal</th><th>Open</th><th>Totaal klant</th><th>Actie</th></tr></thead><tbody>{data.projecten.map(p=>{let t=totals(p.naam),paid=p.status==='Betaald',totaal=p.methode==='Volgens offerte / vaste prijs'?Number(p.offerteBedrag||0):t.totaal;return <tr key={p.projectNr} className={paid?'paid-row':''}><td>{p.projectNr}</td><td>{paid?'✅ ':''}{p.naam}<br/><small>{p.factuurNr||''}</small></td><td>{p.klant}</td><td>{p.methode}</td><td><span className={'badge '+(paid?'green':'')}>{paid?'✅ Betaald':p.status}</span></td><td>{euro(t.arbeid)}</td><td>{euro(t.materiaal)}</td><td>{euro(paid?0:t.materiaal)}</td><td><b>{euro(totaal)}</b></td><td><button className="dark" onClick={()=>setProject(p)}>✏️</button><button className="primary" onClick={()=>setStatus(p.projectNr,'Factureren')}>Factureren</button><button className="primary" onClick={()=>setStatus(p.projectNr,'Factuur verzonden')}>Verzonden</button><button className="primary" onClick={()=>setStatus(p.projectNr,'Betaald')}>Betaald</button></td></tr>})}</tbody></table></div>}
function ProjectDetails({data,totals}){return <Table title="Projectdetails totalen" head={['Project','Uren','Arbeid','Materiaal','Totaal regie','Offerte','Resultaat offerte']} rows={data.projecten.map(p=>{let t=totals(p.naam),off=Number(p.offerteBedrag||0);return[`${p.projectNr} - ${p.naam}`,t.uren.toFixed(2)+' u',euro(t.arbeid),euro(t.materiaal),euro(t.totaal),off?euro(off):'-',off?euro(off-t.arbeid-t.materiaal):'-']})}/>}
function Table({title,head=[],rows=[]}){return <div className={title?'card':''}>{title&&<h2>{title}</h2>}<table><thead><tr>{head.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table></div>}
function SimpleRows({items,cols}){return <Table head={cols} rows={items.map(x=>cols.map(c=>c.toLowerCase().includes('datum')?dnl(x[c]):x[c]))}/>}
