'use client';

import { useEffect, useMemo, useState } from 'react';
import { supabase } from '../lib/supabaseClient';

const empty = { klanten: [], projecten: [], planning: [], uren: [], materiaal: [], uitgaven: [], vrijeDagen: [] };
const cats = ['⛽ Benzine / Tanken','🔌 Auto laden','🚗 Auto onderhoud','🚘 Auto huur','🅿️ Parkeren','✈️ Vlucht','🏨 Overnachting / Hotel','🍔 Eten onderweg','☕ Koffie / Lunch','🍽️ Zakelijk diner','🔧 Gereedschap','🦺 Werkkleding','📱 Telefoon','💻 Software / Abonnementen','📋 Administratie','📦 Overige bedrijfskosten'];

function euro(v){return new Intl.NumberFormat('nl-NL',{style:'currency',currency:'EUR'}).format(Number(v||0))}
function today(){return new Date().toISOString().slice(0,10)}
function formatDateNL(d){if(!d)return'';let p=String(d).split('-');return p.length===3?`${p[2]}/${p[1]}/${p[0].slice(2)}`:d}
function nextNr(prefix, arr, field){let y=String(new Date().getFullYear()), max=0;(arr||[]).forEach(x=>{let m=String(x[field]||'').match(new RegExp('^'+prefix+y+'-(\\\\d+)$')); if(m) max=Math.max(max,parseInt(m[1],10));}); return prefix+y+'-'+String(max+1).padStart(3,'0')}
function mins(t){let [h,m]=String(t||'00:00').split(':').map(Number);return h*60+m}

export default function Home(){
 const [active,setActive]=useState('dashboard');
 const [data,setData]=useState(empty);
 const [klant,setKlant]=useState({type:'Privé'});
 const [project,setProject]=useState({status:'Gepland',methode:'Regie / urenbasis'});
 const [plan,setPlan]=useState({datum:today(),eindDatum:today(),start:'08:00',einde:'16:30'});
 const [uur,setUur]=useState({datum:today(),start:'08:00',einde:'16:30',tarief:35});
 const [mat,setMat]=useState({datum:today(),bedrag:0});
 const [uit,setUit]=useState({datum:today(),categorie:cats[0],bedrag:0,btwPerc:21});
 const [importText,setImportText]=useState('');

 useEffect(()=>{for(const key of ['gioBusinessPlannerV1','gioTestBetaald','gioTestDesktop','gioPlannerDesktop']){const raw=localStorage.getItem(key);if(raw){try{const p=JSON.parse(raw);setData({...empty,...p,vrijeDagen:p.vrijeDagen||p.vrijedagen||[]});break;}catch{}}}},[]);
 useEffect(()=>{localStorage.setItem('gioBusinessPlannerV1',JSON.stringify(data))},[data]);

 function projectTotals(projectNaam){const us=data.uren.filter(x=>x.project===projectNaam), ms=data.materiaal.filter(x=>x.project===projectNaam);const urenSom=us.reduce((s,x)=>s+Number(x.uren||0),0), arbeid=us.reduce((s,x)=>s+Number(x.bedrag||0),0), materiaal=ms.reduce((s,x)=>s+Number(x.bedrag||0),0);return{urenSom,arbeid,materiaal,totaalKlant:arbeid+materiaal}}
 const dash=useMemo(()=>{const omzet=data.uren.reduce((s,x)=>s+Number(x.bedrag||0),0), klantMateriaal=data.materiaal.reduce((s,x)=>s+Number(x.bedrag||0),0), uitgaven=data.uitgaven.reduce((s,x)=>s+Number(x.bedrag||0),0);return{omzet,klantMateriaal,uitgaven,winst:omzet-klantMateriaal-uitgaven,teFactureren:data.projecten.filter(p=>p.status==='Factureren').reduce((s,p)=>s+projectTotals(p.naam).totaalKlant,0),verzonden:data.projecten.filter(p=>p.status==='Factuur verzonden').reduce((s,p)=>s+projectTotals(p.naam).totaalKlant,0),betaald:data.projecten.filter(p=>p.status==='Betaald').reduce((s,p)=>s+projectTotals(p.naam).totaalKlant,0),openMateriaal:data.projecten.filter(p=>p.status!=='Betaald').reduce((s,p)=>s+projectTotals(p.naam).materiaal,0)}},[data]);

 function saveKlant(){if(!klant.naam)return alert('Vul klantnaam in');const item={...klant,klantNr:klant.klantNr||nextNr('K',data.klanten,'klantNr'),gewijzigdOp:new Date().toLocaleString('nl-NL')};setData(d=>({...d,klanten:[...d.klanten.filter(k=>k.klantNr!==item.klantNr),item]}));setKlant({type:'Privé'})}
 function saveProject(){if(!project.naam)return alert('Vul projectnaam in');const item={...project,projectNr:project.projectNr||nextNr('',data.projecten,'projectNr')};setData(d=>({...d,projecten:[...d.projecten.filter(p=>p.projectNr!==item.projectNr),item]}));setProject({status:'Gepland',methode:'Regie / urenbasis'})}
 function setProjectStatus(nr,status){setData(d=>({...d,projecten:d.projecten.map(p=>{if(p.projectNr!==nr)return p;const n={...p,status,statusDatum:new Date().toLocaleString('nl-NL')};if(['Factureren','Factuur verzonden','Betaald'].includes(status)&&!n.factuurNr)n.factuurNr=nextNr('F',d.projecten,'factuurNr');if(status==='Betaald')n.betaaldDatum=today();return n})}))}
 function savePlan(){if(!plan.project)return alert('Kies project');setData(d=>({...d,planning:[...d.planning,{...plan,id:String(Date.now())}]}))}
 function saveUur(){if(!uur.project)return alert('Kies project');let m=mins(uur.einde)-mins(uur.start);if(m<0)m+=1440;const uren=m/60,bedrag=uren*Number(uur.tarief||35);setData(d=>({...d,uren:[...d.uren,{...uur,uren,bedrag}]}))}
 function saveMat(){if(!mat.project)return alert('Kies project');setData(d=>({...d,materiaal:[...d.materiaal,mat]}));setMat({datum:today(),bedrag:0})}
 function saveUit(){const bedrag=Number(uit.bedrag||0), btwPerc=Number(uit.btwPerc||0), btwBedrag=btwPerc>0?bedrag-bedrag/(1+btwPerc/100):0;setData(d=>({...d,uitgaven:[...d.uitgaven,{...uit,btwBedrag}]}));setUit({datum:today(),categorie:cats[0],bedrag:0,btwPerc:21})}
 function exportBackup(){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`GIO_Business_Planner_Backup_${today()}.json`;a.click()}
 function importBackup(){try{const p=JSON.parse(importText);setData({...empty,...p,vrijeDagen:p.vrijeDagen||p.vrijedagen||[]});alert('Back-up geïmporteerd')}catch{alert('Kan JSON niet lezen')}}
 function importFile(e){const file=e.target.files?.[0];if(!file)return;const r=new FileReader();r.onload=()=>setImportText(String(r.result||''));r.readAsText(file)}

 const nav=[['dashboard','🏠 Dashboard'],['klanten','👥 Klanten'],['projecten','📁 Projecten'],['planning','📅 Planning'],['uren','⏱ Uren'],['materiaal','🧰 Materiaal'],['uitgaven','💸 Uitgave / Investeren'],['backup','💾 Back-up / Import'],['dev','🛠 Ontwikkelmodus']];

 return <div className="shell"><aside className="sidebar"><div className="logo">GIO Business Planner</div><div className="sub">planner.gioklusbaas.nl</div><div className="nav">{nav.map(([id,label])=><button key={id} className={active===id?'active':''} onClick={()=>setActive(id)}>{label}</button>)}</div></aside><main className="main"><div className="topbar"><div><b>GIO Business Planner v1.0 testbaar</b><br/><small>{supabase?'Supabase variabelen gevonden':'Offline testmodus'}</small></div><button className="primary" onClick={exportBackup}>💾 Back-up maken</button></div>
 {active==='dashboard'&&<><div className="grid">{[['Omzet',dash.omzet],['Materiaal klant',dash.klantMateriaal],['Uitgaven / Investeren',dash.uitgaven],['Winst',dash.winst],['Te factureren',dash.teFactureren],['Facturen verzonden',dash.verzonden],['Open materiaal',dash.openMateriaal],['Betaald',dash.betaald]].map(([l,v])=><Kpi key={l} label={l} value={v}/>)}</div><ProjectTable data={data} projectTotals={projectTotals} setProject={setProject} setProjectStatus={setProjectStatus}/></>}
 {active==='klanten'&&<><div className="card"><h2>👥 Klant toevoegen / wijzigen</h2><div className="row"><Field label="Type"><select value={klant.type||'Privé'} onChange={e=>setKlant({...klant,type:e.target.value})}><option>Privé</option><option>Zakelijk</option></select></Field>{['naam','contact','adres','postcode','plaats','telefoon','email','kvk','btw'].map(f=><Field key={f} label={f}><input value={klant[f]||''} onChange={e=>setKlant({...klant,[f]:e.target.value})}/></Field>)}</div><button className="primary" onClick={saveKlant}>Klant opslaan</button></div><div className="card"><h2>Klantenbestand</h2><table><thead><tr><th>Klantnr.</th><th>Type</th><th>Naam</th><th>Plaats</th><th>Telefoon</th><th>E-mail</th><th>Wijzig</th><th></th></tr></thead><tbody>{data.klanten.map(k=><tr key={k.klantNr}><td>{k.klantNr}</td><td>{k.type}</td><td>{k.naam}</td><td>{k.plaats}</td><td>{k.telefoon}</td><td>{k.email}</td><td><button className="dark" onClick={()=>setKlant(k)}>✏️</button></td><td><button className="red" onClick={()=>setData(d=>({...d,klanten:d.klanten.filter(x=>x.klantNr!==k.klantNr)}))}>🗑️</button></td></tr>)}</tbody></table></div></>}
 {active==='projecten'&&<><ProjectForm data={data} project={project} setProject={setProject} saveProject={saveProject}/><ProjectTable data={data} projectTotals={projectTotals} setProject={setProject} setProjectStatus={setProjectStatus}/></>}
 {active==='planning'&&<div className="card"><h2>📅 Planning / meerdaagse projecten</h2><div className="row"><Field label="Project"><select value={plan.project||''} onChange={e=>setPlan({...plan,project:e.target.value})}><option value="">Kies project</option>{data.projecten.map(p=><option key={p.projectNr}>{p.naam}</option>)}</select></Field><Field label="Startdatum"><input type="date" value={plan.datum||today()} onChange={e=>setPlan({...plan,datum:e.target.value})}/></Field><Field label="Einddatum"><input type="date" value={plan.eindDatum||today()} onChange={e=>setPlan({...plan,eindDatum:e.target.value})}/></Field><Field label="Starttijd"><input type="time" value={plan.start||''} onChange={e=>setPlan({...plan,start:e.target.value})}/></Field><Field label="Eindtijd"><input type="time" value={plan.einde||''} onChange={e=>setPlan({...plan,einde:e.target.value})}/></Field><Field label="Notitie"><input value={plan.notitie||''} onChange={e=>setPlan({...plan,notitie:e.target.value})}/></Field></div><button className="primary" onClick={savePlan}>Planning opslaan</button><table><thead><tr><th>Project</th><th>Van</th><th>Tot</th><th>Tijd</th><th>Notitie</th></tr></thead><tbody>{data.planning.map((p,i)=><tr key={i}><td>{p.project}</td><td>{formatDateNL(p.datum)}</td><td>{formatDateNL(p.eindDatum)}</td><td>{p.start} - {p.einde}</td><td>{p.notitie}</td></tr>)}</tbody></table></div>}
 {active==='uren'&&<div className="card"><h2>⏱ Uren registreren</h2><div className="row"><Field label="Datum"><input type="date" value={uur.datum||today()} onChange={e=>setUur({...uur,datum:e.target.value})}/></Field><Field label="Klant"><select value={uur.klant||''} onChange={e=>setUur({...uur,klant:e.target.value})}><option value="">Kies klant</option>{data.klanten.map(k=><option key={k.klantNr}>{k.naam}</option>)}</select></Field><Field label="Project"><select value={uur.project||''} onChange={e=>setUur({...uur,project:e.target.value})}><option value="">Kies project</option>{data.projecten.map(p=><option key={p.projectNr}>{p.naam}</option>)}</select></Field>{['start','einde','tarief'].map(f=><Field key={f} label={f}><input type={f==='tarief'?'number':'time'} value={uur[f]||''} onChange={e=>setUur({...uur,[f]:e.target.value})}/></Field>)}</div><button className="primary" onClick={saveUur}>Uren opslaan</button><table><thead><tr><th>Datum</th><th>Klant</th><th>Project</th><th>Start</th><th>Einde</th><th>Uren</th><th>Bedrag</th></tr></thead><tbody>{data.uren.map((u,i)=>{const paid=data.projecten.find(p=>p.naam===u.project)?.status==='Betaald';return <tr key={i} className={paid?'paid-row':''}><td>{formatDateNL(u.datum)}</td><td>{u.klant}</td><td>{paid?'✅ ':''}{u.project}</td><td>{u.start}</td><td>{u.einde}</td><td>{Number(u.uren||0).toFixed(2)}</td><td>{euro(u.bedrag)}</td></tr>})}</tbody></table></div>}
 {active==='materiaal'&&<div className="card"><h2>🧰 Materiaal klant</h2><div className="row"><Field label="Datum"><input type="date" value={mat.datum||today()} onChange={e=>setMat({...mat,datum:e.target.value})}/></Field><Field label="Project"><select value={mat.project||''} onChange={e=>setMat({...mat,project:e.target.value})}><option value="">Kies project</option>{data.projecten.map(p=><option key={p.projectNr}>{p.naam}</option>)}</select></Field>{['lev','oms','bedrag','pdfNaam'].map(f=><Field key={f} label={f}><input type={f==='bedrag'?'number':'text'} value={mat[f]||''} onChange={e=>setMat({...mat,[f]:e.target.value})}/></Field>)}</div><button className="primary" onClick={saveMat}>Materiaal opslaan</button></div>}
 {active==='uitgaven'&&<div className="card"><h2>💸 Uitgave / Investeren</h2><div className="row"><Field label="Datum"><input type="date" value={uit.datum||today()} onChange={e=>setUit({...uit,datum:e.target.value})}/></Field><Field label="Categorie"><select value={uit.categorie||''} onChange={e=>setUit({...uit,categorie:e.target.value})}>{cats.map(c=><option key={c}>{c}</option>)}</select></Field>{['leverancier','omschrijving','bedrag','btwPerc'].map(f=><Field key={f} label={f}><input type={['bedrag','btwPerc'].includes(f)?'number':'text'} value={uit[f]||''} onChange={e=>setUit({...uit,[f]:e.target.value})}/></Field>)}</div><button className="primary" onClick={saveUit}>Uitgave opslaan</button></div>}
 {active==='backup'&&<div className="card"><h2>💾 Back-up / Import</h2><div className="notice"><b>Belangrijk:</b> hiermee nemen we jouw oude testdata mee. Maak in je oude HTML-testversie eerst een JSON-back-up, importeer die hier, en daarna zetten we de data later naar Supabase.</div><br/><button className="primary" onClick={exportBackup}>💾 Back-up maken</button><label>JSON-bestand kiezen</label><input type="file" accept=".json" onChange={importFile}/><label>JSON plakken</label><textarea value={importText} onChange={e=>setImportText(e.target.value)}/><button className="dark" onClick={importBackup}>📥 Importeren</button><h3>Preview data</h3><div className="code">{JSON.stringify(data,null,2).slice(0,5000)}</div></div>}
 {active==='dev'&&<div className="card"><h2>🛠 Ontwikkelmodus</h2><div className="dev"><b>Versie:</b> 1.0.0-testbaar<br/><b>Status:</b> klaar om via GitHub + Vercel te testen<br/><b>Supabase:</b> {supabase?'gevonden':'nog niet actief'}<br/><br/>✔ Dashboard<br/>✔ Klanten privé/zakelijk<br/>✔ Projecten met projectnummer/factuurnummer<br/>✔ Meerdaagse planning<br/>✔ Uren<br/>✔ Materiaal<br/>✔ Uitgaven / Investeren<br/>✔ Offerte of regie<br/>✔ Betaald-status<br/>✔ Back-up/import<br/><br/>Volgende stap: Supabase live opslaan, PDF factuur, werkbon, bonfoto upload.</div></div>}
 </main></div>
}

function Field({label,children}){return <div><label>{label}</label>{children}</div>}
function Kpi({label,value}){return <div className="kpi"><small>{label}</small><b>{euro(value)}</b></div>}
function ProjectForm({data,project,setProject,saveProject}){return <div className="card"><h2>📁 Project toevoegen / wijzigen</h2><div className="row"><Field label="Projectnaam"><input value={project.naam||''} onChange={e=>setProject({...project,naam:e.target.value})}/></Field><Field label="Klant"><select value={project.klant||''} onChange={e=>setProject({...project,klant:e.target.value})}><option value="">Kies klant</option>{data.klanten.map(k=><option key={k.klantNr}>{k.naam}</option>)}</select></Field><Field label="Status"><select value={project.status||'Gepland'} onChange={e=>setProject({...project,status:e.target.value})}>{['Offerte','Gepland','In uitvoering','Werk done','Factureren','Factuur verzonden','Betaald'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Facturatiemethode"><select value={project.methode||'Regie / urenbasis'} onChange={e=>setProject({...project,methode:e.target.value})}><option>Regie / urenbasis</option><option>Volgens offerte / vaste prijs</option></select></Field><Field label="Offertebedrag"><input type="number" value={project.offerteBedrag||''} onChange={e=>setProject({...project,offerteBedrag:e.target.value})}/></Field><Field label="Startdatum"><input type="date" value={project.start||''} onChange={e=>setProject({...project,start:e.target.value})}/></Field><Field label="Einddatum"><input type="date" value={project.eind||''} onChange={e=>setProject({...project,eind:e.target.value})}/></Field></div><button className="primary" onClick={saveProject}>Project opslaan</button></div>}
function ProjectTable({data,projectTotals,setProject,setProjectStatus}){return <div className="card"><h2>📁 Projectoverzicht</h2><table><thead><tr><th>Projectnr.</th><th>Project</th><th>Klant</th><th>Methode</th><th>Status</th><th>Arbeid</th><th>Materiaal</th><th>Open</th><th>Totaal klant</th><th>Actie</th></tr></thead><tbody>{data.projecten.map(p=>{const t=projectTotals(p.naam),paid=p.status==='Betaald',totaal=p.methode==='Volgens offerte / vaste prijs'?Number(p.offerteBedrag||0):t.totaalKlant;return <tr key={p.projectNr} className={paid?'paid-row':''}><td>{p.projectNr}</td><td>{paid?'✅ ':''}{p.naam}<br/><small>{p.factuurNr||''}</small></td><td>{p.klant}</td><td>{p.methode}</td><td><span className={`badge ${paid?'green':''}`}>{paid?'✅ Betaald':p.status}</span></td><td>{euro(t.arbeid)}</td><td>{euro(t.materiaal)}</td><td>{euro(paid?0:t.materiaal)}</td><td><b>{euro(totaal)}</b></td><td><button className="dark" onClick={()=>setProject(p)}>✏️</button><button className="primary" onClick={()=>setProjectStatus(p.projectNr,'Factureren')}>Factureren</button><button className="primary" onClick={()=>setProjectStatus(p.projectNr,'Betaald')}>✅ Betaald</button></td></tr>})}</tbody></table></div>}
