-- GIO Business Planner v1.0 LIVE cloud opslag
-- Voer dit uit in Supabase SQL Editor.

create table if not exists planner_data (
  user_id uuid primary key references auth.users(id) on delete cascade,
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz default now()
);

alter table planner_data enable row level security;

drop policy if exists "Users can read own planner data" on planner_data;
create policy "Users can read own planner data"
on planner_data for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can insert own planner data" on planner_data;
create policy "Users can insert own planner data"
on planner_data for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can update own planner data" on planner_data;
create policy "Users can update own planner data"
on planner_data for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create table if not exists app_changelog (
  id bigint generated by default as identity primary key,
  version text,
  note text,
  created_at timestamptz default now()
);
